// <auto-generated />
namespace VirtoCommerce.StoreModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StoreFulfillmentCenters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreFulfillmentCenters));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191240055_StoreFulfillmentCenters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
